services:
  LegalClinic:
    image: postgres
    container_name: LegalClinic
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: LegalClinc_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: LegalClinic

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_api
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.dev
    depends_on:
      - Legalclinic

volumes:
  postgres_data: